version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: green-groves-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: green-groves-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./backend/database:/var/www/html/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://13.211.146.7:8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    restart: unless-stopped
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: green-groves-frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    restart: unless-stopped
